"use strict";
/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 12/5/2025, 1:04:36 PM
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.quizPages = void 0;
exports.quizPages = [
    {
        "id": "docs-example-exam",
        "name": "example-exam",
        "quizzes": [
            {
                "id": "example-exam#example",
                "name": "Example",
                "src": "Example.md"
            }
        ]
    }
];
