/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 11/1/2025, 1:35:56 AM
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
  src?: string | null;   // <-- new field
}

export const quizPages: QuizPage[] = [
  {
    "id": "docs-chapter-02-03_executing",
    "name": "executing",
    "quizzes": [
      {
        "id": "chapter-02/executing#executing+rf",
        "name": "Executing RF",
        "src": "test.md"
      }
    ]
  },
  {
    "id": "docs-example-exam",
    "name": "example-exam",
    "quizzes": [
      {
        "id": "example-exam#example1",
        "name": "example1",
        "src": "exam.md"
      },
      {
        "id": "example-exam#example2",
        "name": "example2",
        "src": "test.md"
      }
    ]
  }
];
