// scripts/generateQuizComponentList.js
const fs = require('fs');
const path = require('path');
const { randomUUID } = require('crypto');

function getMarkdownFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return getMarkdownFiles(fullPath);
    }
    if (entry.isFile() && (fullPath.endsWith('.md') || fullPath.endsWith('.mdx'))) {
      return [fullPath];
    }
    return [];
  });
}


function extractComponentProps(content, componentName) {
  const tagRegex = new RegExp(`<${componentName}(\\s+[^>]*?)?>`, 'gi');
  const components = [];

  let match;
  while ((match = tagRegex.exec(content)) !== null) {
    const propsString = match[1] || '';

    const nameMatch = /name\s*=\s*["']([^"']+)["']/i.exec(propsString);

    if (nameMatch) {
      components.push({
        name: nameMatch[1],
      });
    }
  }

  return components;
}


function findComponentUsage(rootDir, componentName) {
  const files = getMarkdownFiles(rootDir);
  const cwd = process.cwd();

  const results = [];


  for (const file of files) {
    const content = fs.readFileSync(file, 'utf-8');
    const matches = extractComponentProps(content, componentName);

    // Remove file ending
    const pagePath = path.relative(cwd, file).split(".")[0];


    const pageParts = pagePath.split("/");
    const page = removeFollowingElementsInArray(pageParts);

    matches.forEach((match) => {
      let id = page.replace("docs/", "") + "#" + match.name.replace(" ", "+");

      // Remove numbers followed by an underscore (e.g., '03_' becomes '')
      id = id.replace(/\b\d+_/g, "");

      id = id.toLowerCase();
      results.push({
        page: page,
        name: match.name,
        id: id,
      });
    });
  }

  return results;
}

function organizeQuizzesByPage(components) {
  const quizPages = {};

  for (const component of components) {
    const pagePath = component.page;

    if (!quizPages[pagePath]) {
      quizPages[pagePath] = {
        id: pagePath.replace(/\//g, "-"),
        name: pagePath.split("/").pop().replace(/^\d+_/, ""),
        quizzes: []
      };
    }

    quizPages[pagePath].quizzes.push({
      id: component.id,
      name: component.name
    });
  }

  return Object.values(quizPages);
}


function writeComponentListToFile(components, outputFilePath) {
  const date = new Date().toLocaleString();
  const header = `/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: ${date}
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
}

`;

  const quizPages = organizeQuizzesByPage(components);
  const content = `export const quizPages: QuizPage[] = ${JSON.stringify(quizPages, null, 2)};`;

  const fullContent = header + content + '\n';
  fs.writeFileSync(outputFilePath, fullContent, 'utf-8');
  console.log(`Generated ${outputFilePath} with ${quizPages.length} quiz pages and ${components.length} total quizzes.`);
}

function removeFollowingElementsInArray(arr) {
  let result = [];
  let lastValue = null;

  for (let item of arr) {
    const lowerItem = item.toLowerCase();
    if (lowerItem !== lastValue) {
      result.push(item);
      lastValue = lowerItem;
    }
  }

  return result.join("/");
}

const componentName = 'Quiz';
const rootDir = path.resolve(process.cwd(), 'docs');
const outputFilePath = path.resolve(process.cwd(), 'src/components/Quiz/quizComponents.ts');

const quizComponents = findComponentUsage(rootDir, componentName);
writeComponentListToFile(quizComponents, outputFilePath);